version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.2.0
    ports:
      - "8080:8080"
    environment:
      API_KEY: lidiakey # This will be generated automatically
      CACHE_REDIS_ENABLED: true
      CACHE_REDIS_URI: redis://default:dd87578fae3c3f066a0f@evolution_redis:6379
      DATABASE_ENABLED: true
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: "postgresql://user:password@evolution_db:5432/evolution_db?schema=public"
      DATABASE_CONNECTION_CLIENT_NAME: evolution_exchange
      DATABASE_SAVE_DATA_INSTANCE: true
      DATABASE_SAVE_DATA_NEW_MESSAGE: true
      DATABASE_SAVE_MESSAGE_UPDATE: true
      DATABASE_SAVE_DATA_CONTACTS: true
      DATABASE_SAVE_DATA_CHATS: true
      DATABASE_SAVE_DATA_LABELS: true
      DATABASE_SAVE_DATA_HISTORIC: true
    depends_on:
      - evolution_db
      - evolution_redis

  evolution_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evolution_db
    ports:
      - "5433:5432" # Expose a different port for the evolution database

  evolution_redis:
    image: redis:latest
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: dd87578fae3c3f066a0f
    ports:
      - "6379:6379" # Expose Redis on the default port

  backend:
    depends_on:
      - backend_db
      - evolution_db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Adjust based on your backend service port

  backend_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
      POSTGRES_DB: backend_db
    ports:
      - "5435:5432"  # Expose a different port for the backend database
